export const FOURSQUARE = "FOURSQUARE"
export const RETTY = "RETTY"
export const WONGNAI = "WONGNAI"
export const RESTAURANTGURU = "RESTAURANTGURU"
export const OPENRICE = "OPENRICE"

export const FOURSQUARE_DESCRIPTION = "แอพมือถือค้นหาและค้นพบในท้องถิ่นที่พัฒนาโดย Foursquare Labs Inc..."
export const RETTY_DESCRIPTION = "โซเชียลมีเดียสำหรับคนรักอาหาร รวบรวมร้านอร่อยที่เชื่อถือได้โดยสายกินตัวจริง..."
export const WONGNAI_DESCRIPTION = "เว็บสำหรับค้นหาร้านอาหาร เมนูอาหาร สูตรอาหารและวิธีทำ โรงแรม ที่พัก และอื่นๆ"
export const RESTAURANTGURU_DESCRIPTION = "เว็บที่ช่วยให้คุณค้นพบสถานที่รับประทานอาหารดีๆ ใกล้สถานที่ของคุณ... "
export const OPENRICE_DESCRIPTION = "เว็บไซต์แนะนำร้านอาหาร รวมรีวิวร้านอาหารเด็ดและรูปภาพอาหาร... "
